awsAccount: "350794894992"
awsRegion: 'ap-northeast-1'
stage: "production"
serviceName: "kskkido"
applicationStackName: "kskkido-application-production"
blogServiceName: "kskkido-blog"
blogS3BucketName: "kskkido-blog-production"
blogSourceFilePath: "packages/kskkido-blog/.build"
blogTargetFilePath: "/"
blogMetadataFileName: "_metadata.json"
deploymentStackName: "kskkido-deployment-production"
deployRoleName: "kskkido-deploy-role-production"
deployUserName: "personal"
deployCiUserName: "ci"
domainName: "kskkido.com"
certificateArn: "arn:aws:acm:us-east-1:350794894992:certificate/b8422ad3-441f-4e7e-bd8c-caeda81c6315"
